### ISSUE TITLE
add requirements.txt

### ISSUE THREAD

**Issue by cthoyt** [scolby33/pushover_complete#2]
I think the only requirement so far is `requests`. Is it explicitly stated somewhere in the code or the registration with pypi that it needs `requests`? Does requirements.txt solve this?

This is disregarding the test modules, which use `tox` and other things, but this isn't necessary for users to install.

Edit: found it in `setup.py`. Would it be better to make this external as a requirements file?

**Comment by scolby33** [comment]
`pip install [-e] .` should handle this, as you figured out.

Perhaps a requirements.txt along these lines would help?
```
-e .
```
All it is is a list of arguments to `pip`, right?
https://caremad.io/2013/07/setup-vs-requirement/

(Check out the last code snippet in this section in [the docs](http://pushover-complete.readthedocs.io/en/develop/contributing.html#setup))

**Comment by cthoyt** [comment]
ugh... fine... after that (definitely should have had a TLDR) I still don't feel like it matters
